### ISSUE TITLE
Please consider publishing a production ready package on NPM

### ISSUE THREAD

**Issue by nemchik** [DocuWare/REST-Sample-TS#4]
It would be amazing to be able to init an empty node project and run something like `npm install docuware-api` and then develop a project that makes use of the ability to easily specify the required information (variables containing credentials, etc) and interact with a DocuWare system. Here is an example package for QuickBooks that displays the idea I'm hoping to see here https://www.npmjs.com/package/quickbooks

With the version management in Node/NPM and using semver it should be fairly simple to maintain releases of an npm package that would be compatible with specific versions of DocuWare.

This idea would possibly warrant a separate code repository, but it seems like the restWrapper contains most (if not all) of the ground work to make this possible.

**Comment by VidensKnowledge** [comment]
Hey gents! First of all, thanks for publishing this and the Validations repo, looking forward to working with them. 

Is this repo designed to work with Cloud or does it only work with on-premises systems? 

I keep getting the following error when I try to connect to our demo cloud account: 
Error message:
Error: connect EADDRNOTAVAIL 52.154.45.167 - Local (0.0.0.0:50772)
Error Stack:
RequestError: Error: connect EADDRNOTAVAIL 52.154.45.167 - Local (0.0.0.0:50772)
    at new RequestError (J:\elf\REST-Sample-TS\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (J:\elf\REST-Sample-TS\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (J:\elf\REST-Sample-TS\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (J:\elf\REST-Sample-TS\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (J:\elf\REST-Sample-TS\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:327:22)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)

I'm a relative newbie at all of this, but some help with getting over this obstacle would be much appreciated. Thank you!
